### ISSUE TITLE
Forbidden Reach Races: Wrong records

### ISSUE THREAD

**Issue by Kepas-Beleglorn** [hasore/DragonRidingRace#2]
At least the Morqut Ascent and the Forbidden Reach Rush show the times from the Thaldraszus race The Flowing Forest Flight. So far I couldn't find the reason within the code.
![184519_World of Warcraft](https://user-images.githubusercontent.com/77459606/228616510-bad8c82c-00d6-4afe-89dc-2a445d359109.png)

**Comment by hasore** [comment]
A fix will be available for release 0.2.2

**Comment by hasore** [comment]
fixed
